import { Component } from '@angular/core';
import { Product } from '../../../../app/app.interface';
import { CategoriesComponent } from '../categories.component';

@Component({
  selector: 'app-smartphones',
  standalone: true,
  imports: [CategoriesComponent],
  templateUrl: './smartphones.component.html',
  styleUrl: './smartphones.component.scss'
})
export class SmartphonesComponent {
 products: Product[] = [];
  ngOnInit(): void {
    this.products = this.getProducts();
  }
  getProducts(): Product[] {
    return [
      {
        id: 1,
        title: 'iPhone 15 Case',
        category: 'Case',
        brand: 'Spigen',
        price: 25.99,
        color: 'Black',
        discountPercentage: [],
        thumbnail: 'Silicone',
        stock: 50,
        rating: 4.95,
        description: 'iPhone 15, iPhone 15 Pro',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.Xqszq9NBy6gj2nLBj2iSaQHaHa?rs=1&pid=ImgDetMain",
      },
      {
        id: 2,
        title: 'Galaxy S23 Protector',
        category: 'Screen Protector',
        brand: 'Belkin',
        price: 14.99,
        color: 'Transparent',
        discountPercentage: [''],
        thumbnail: 'Tempered Glass',
        stock: 100,
        rating: 4.99,
        description: 'Samsung Galaxy S23',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.z1B-wwvIacHVlWhR559dSAHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain",
      },
      {
        id: 3,
        title: 'Wireless Charger',
        category: 'Charger',
        brand: 'Anker',
        price: 39.99,
        color: 'White',
        discountPercentage: ['iPhone', 'Samsung', 'Pixel'],
        thumbnail: 'Plastic',
        stock: 30,
        rating: 4.81,
        description: 'iPhone, Samsung, Pixel',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/R.aca59ecbebe748985e2649bf26be8288?rik=ENpD7gE822HTfg&riu=http%3a%2f%2fwm.cdn.cn86.cn%2fnanami%2f2022%2f10%2fdbac8b9fb7vy4fo9.jpg&ehk=5FO6bQwFZ%2bvau5iB3Vwf%2fvfmz%2bnVRyhqXQWYE471964%3d&risl=&pid=ImgRaw&r=0",
      },
      {
        id: 1,
        title: 'iPhone 15 Case',
        category: 'Case',
        brand: 'Spigen',
        price: 25.99,
        color: 'Black',
        discountPercentage: [],
        thumbnail: 'Silicone',
        stock: 50,
        rating: 4.95,
        description: 'iPhone 15, iPhone 15 Pro',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.Xqszq9NBy6gj2nLBj2iSaQHaHa?rs=1&pid=ImgDetMain",
      },
      {
        id: 2,
        title: 'Galaxy S23 Protector',
        category: 'Screen Protector',
        brand: 'Belkin',
        price: 14.99,
        color: 'Transparent',
        discountPercentage: [''],
        thumbnail: 'Tempered Glass',
        stock: 100,
        rating: 4.99,
        description: 'Samsung Galaxy S23',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.z1B-wwvIacHVlWhR559dSAHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain",
      },
      {
        id: 3,
        title: 'Wireless Charger',
        category: 'Charger',
        brand: 'Anker',
        price: 39.99,
        color: 'White',
        discountPercentage: ['iPhone', 'Samsung', 'Pixel'],
        thumbnail: 'Plastic',
        stock: 30,
        rating: 4.81,
        description: 'iPhone, Samsung, Pixel',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/R.aca59ecbebe748985e2649bf26be8288?rik=ENpD7gE822HTfg&riu=http%3a%2f%2fwm.cdn.cn86.cn%2fnanami%2f2022%2f10%2fdbac8b9fb7vy4fo9.jpg&ehk=5FO6bQwFZ%2bvau5iB3Vwf%2fvfmz%2bnVRyhqXQWYE471964%3d&risl=&pid=ImgRaw&r=0",
      },
      {
        id: 1,
        title: 'iPhone 15 Case',
        category: 'Case',
        brand: 'Spigen',
        price: 25.99,
        color: 'Black',
        discountPercentage: [],
        thumbnail: 'Silicone',
        stock: 50,
        rating: 4.95,
        description: 'iPhone 15, iPhone 15 Pro',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.Xqszq9NBy6gj2nLBj2iSaQHaHa?rs=1&pid=ImgDetMain",
      },
      {
        id: 2,
        title: 'Galaxy S23 Protector',
        category: 'Screen Protector',
        brand: 'Belkin',
        price: 14.99,
        color: 'Transparent',
        discountPercentage: [''],
        thumbnail: 'Tempered Glass',
        stock: 100,
        rating: 4.99,
        description: 'Samsung Galaxy S23',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.z1B-wwvIacHVlWhR559dSAHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain",
      },
      {
        id: 3,
        title: 'Wireless Charger',
        category: 'Charger',
        brand: 'Anker',
        price: 39.99,
        color: 'White',
        discountPercentage: ['iPhone', 'Samsung', 'Pixel'],
        thumbnail: 'Plastic',
        stock: 30,
        rating: 4.81,
        description: 'iPhone, Samsung, Pixel',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/R.aca59ecbebe748985e2649bf26be8288?rik=ENpD7gE822HTfg&riu=http%3a%2f%2fwm.cdn.cn86.cn%2fnanami%2f2022%2f10%2fdbac8b9fb7vy4fo9.jpg&ehk=5FO6bQwFZ%2bvau5iB3Vwf%2fvfmz%2bnVRyhqXQWYE471964%3d&risl=&pid=ImgRaw&r=0",
      },
      {
        id: 1,
        title: 'iPhone 15 Case',
        category: 'Case',
        brand: 'Spigen',
        price: 25.99,
        color: 'Black',
        discountPercentage: [],
        thumbnail: 'Silicone',
        stock: 50,
        rating: 4.95,
        description: 'iPhone 15, iPhone 15 Pro',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.Xqszq9NBy6gj2nLBj2iSaQHaHa?rs=1&pid=ImgDetMain",
      },
      {
        id: 2,
        title: 'Galaxy S23 Protector',
        category: 'Screen Protector',
        brand: 'Belkin',
        price: 14.99,
        color: 'Transparent',
        discountPercentage: [''],
        thumbnail: 'Tempered Glass',
        stock: 100,
        rating: 4.99,
        description: 'Samsung Galaxy S23',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.z1B-wwvIacHVlWhR559dSAHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain",
      },
      {
        id: 3,
        title: 'Wireless Charger',
        category: 'Charger',
        brand: 'Anker',
        price: 39.99,
        color: 'White',
        discountPercentage: ['iPhone', 'Samsung', 'Pixel'],
        thumbnail: 'Plastic',
        stock: 30,
        rating: 4.81,
        description: 'iPhone, Samsung, Pixel',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/R.aca59ecbebe748985e2649bf26be8288?rik=ENpD7gE822HTfg&riu=http%3a%2f%2fwm.cdn.cn86.cn%2fnanami%2f2022%2f10%2fdbac8b9fb7vy4fo9.jpg&ehk=5FO6bQwFZ%2bvau5iB3Vwf%2fvfmz%2bnVRyhqXQWYE471964%3d&risl=&pid=ImgRaw&r=0",
      },
      {
        id: 1,
        title: 'iPhone 15 Case',
        category: 'Case',
        brand: 'Spigen',
        price: 25.99,
        color: 'Black',
        discountPercentage: [],
        thumbnail: 'Silicone',
        stock: 50,
        rating: 4.95,
        description: 'iPhone 15, iPhone 15 Pro',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.Xqszq9NBy6gj2nLBj2iSaQHaHa?rs=1&pid=ImgDetMain",
      },
      {
        id: 2,
        title: 'Galaxy S23 Protector',
        category: 'Screen Protector',
        brand: 'Belkin',
        price: 14.99,
        color: 'Transparent',
        discountPercentage: [''],
        thumbnail: 'Tempered Glass',
        stock: 100,
        rating: 4.99,
        description: 'Samsung Galaxy S23',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.z1B-wwvIacHVlWhR559dSAHaHa?w=1000&h=1000&rs=1&pid=ImgDetMain",
      },
      {
        id: 3,
        title: 'Wireless Charger',
        category: 'Charger',
        brand: 'Anker',
        price: 39.99,
        color: 'White',
        discountPercentage: ['iPhone', 'Samsung', 'Pixel'],
        thumbnail: 'Plastic',
        stock: 30,
        rating: 4.81,
        description: 'iPhone, Samsung, Pixel',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/R.aca59ecbebe748985e2649bf26be8288?rik=ENpD7gE822HTfg&riu=http%3a%2f%2fwm.cdn.cn86.cn%2fnanami%2f2022%2f10%2fdbac8b9fb7vy4fo9.jpg&ehk=5FO6bQwFZ%2bvau5iB3Vwf%2fvfmz%2bnVRyhqXQWYE471964%3d&risl=&pid=ImgRaw&r=0",
      },
      {
        id: 1,
        title: 'iPhone 15 Case',
        category: 'Case',
        brand: 'Spigen',
        price: 25.99,
        color: 'Black',
        discountPercentage: [],
        thumbnail: 'Silicone',
        stock: 50,
        rating: 4.95,
        description: 'iPhone 15, iPhone 15 Pro',
        onSale: false,
        Sale: undefined,
        images: "https://th.bing.com/th/id/OIP.Xqszq9NBy6gj2nLBj2iSaQHaHa?rs=1&pid=ImgDetMain",
      },
    ];
  }
}
